---
- hosts: "asfservers"
  tasks:
  - name: Pull asf image
    docker_image:
      name: justarchi/archisteamfarm
      source: pull
    register: pull
  - name: Stop asf container
    docker_container:
      name: asf
      state: stopped
    ignore_errors: yes
    when: pull.changed
  - name: Remove asf container
    docker_container:
      name: asf
      state: absent
    ignore_errors: yes
    when: pull.changed
  - name: Create asf container
    docker_container:
      name: asf
      image: justarchi/archisteamfarm
      restart_policy: always
      volumes:
        - /opt/asf/config:/app/config
      ports:
        - "127.0.0.1:1242:1242"
